# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'OpenBreweryChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenBreweryChallenge
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwifterSwift'
  pod 'SwiftLint'

  target 'OpenBreweryChallengeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'OpenBreweryChallengeUITests' do
    # Pods for testing
  end

end
